apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app.kubernetes.io/instance: phpmyadmin
    app.kubernetes.io/name: phpmyadmin
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  - port: 443
    targetPort: 8443
