---
apiVersion: v1
kind: Service
metadata:
  name: ext
  namespace: production
spec:
  ports:
  - name: app
    port: 8080
    protocol: TCP
    targetPort: 8080
  clusterIP: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ext
  namespace: production
spec:
  rules:
  - http:
      paths:
      - path: /ext
        pathType: Exact
        backend:
          service:
            name: ext
            port:
              number: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ext
  namespace: production
subsets:
- addresses:
  - ip: 213.180.193.58
  ports:
  - name: external-api
    port: 80
    protocol: TCP
...
