---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: clickhouse
    hostname: clickhouse
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    published_ports:
      - "0.0.0.0:9000:9000/tcp"
      - "[::]:9000:9000/tcp"
      - "0.0.0.0:8123:8123/tcp"
      - "[::]:8123:8123/tcp"
  - name: vector
    hostname: vector
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: lighthouse
    hostname: lighthouse
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    published_ports:
      - "0.0.0.0:8080:8080/tcp"
      - "[::]:8080:8080/tcp"
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
  check_sequence:
    - dependency
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - dependency
    - lint
    - syntax
    - destroy
    - create
    - converge
    - idempotence
    - cleanup
    - verify
    - destroy
...
