---
version: '2.4'

services:

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - "9100:9100"
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    user: "${USER}:${USER}"
    volumes:
      - ./data/prometheus:/prometheus/
      - ./data/prom-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - node_exporter

  grafana:
    image: "grafana/grafana-oss"
    container_name: grafana
    user: "${USER}:${USER}"
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

...
