version: "3.7"

services:
  frontend:
    image: artemshtepa/netology-app:frontend
    build: ./frontend
    ports:
      - 8000:80

  backend:
    image: artemshtepa/netology-app:backend
    build: ./backend
    links:
      - db
    ports:
      - 9000:9000

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: news
