---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - name: {{ .Release.Name }}-backend-port
      port: {{ .Values.backend.port_ext | default .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
...
