---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.db.use_nfs }}
  storageClassName: "nfs"
  {{- end }}
  accessModes:
    - ReadWrite{{- if .Values.db.use_nfs }}Many{{- else }}Once{{- end }}
  resources:
    requests:
      storage: {{ .Values.db.size }}
...
