---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  login: {{ .Values.db.user | default (randAlpha 10) | b64enc }}
  password: {{ .Values.db.password | default (randAlphaNum 20) | b64enc }}
...
