---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ext-ing
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Values.external.path }}"
        pathType: Exact
        backend:
          service:
            name: {{ .Release.Name }}-ext-svc
            port:
              number: {{ .Values.external.middle_port }}
...
