---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-ext-svc
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.external.ip }}
  ports:
  - name: {{ .Release.Name }}-api
    port: {{ .Values.external.port }}
    protocol: TCP
...
