---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ext-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: {{ .Release.Name }}-app
    port: {{ .Values.external.middle_port }}
    protocol: TCP
    targetPort: {{ .Values.external.middle_port }}
...
