---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - name: {{ .Release.Name }}-frontend-port
      port: {{ .Values.frontend.port_ext | default .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
...
